### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by ksol** [Scalingo/scalingo-ruby-api#13]
Meta-issue to track the work that is left to be done before a `3.0.0` stable release. May evolve over time.

- [x] Specs work. APIs interactions have good coverage, but not the higher level use of the gem (#15 #16 #17)
- [x] Async operations. Some requests trigger a background operation that can be followed via a dedicated endpoint. This endpoint is available, but we could propose a method on the response to inspect it directly. (#15)
- [x] inspect configuration. Configuration is done globally at the moment, and some things may be missing. We may want to allow per-client configuration as well. (#17)
- [x] inspect dependencies. We don't have many, but let's make sure the version we need all of them and that the versions constraint are appropriate. (#17)
- [ ] WS/Streaming. Nothing is done related to those matter. We don't want to add more dependencies than needed, so we'll have to make choices on what we want to include in this gem. This may end up being an officially-supported extension.
- [ ] Documentation and rdoc. Let's document this gem better. Examples are nice, but they only go so far.
- [ ] (3.0 or 3.1) Some endpoints are missing. This is loosely related to the state of our [developers documentation](https://developers.scalingo.com), but some endpoints are not publicly documented, some are not in this gem, and some are both of those. (#14)
- [ ] Deprecate v2 + post install message, as a mean of advertising that the gem name has changed

**Comment by EtienneM** [comment]
I don't know if it's a step you want to add in this list. But when we release the v3, we probably want to deprecate the old gem to force users to move to this new gem, don't we?

**Comment by ksol** [comment]
Right. We'll push a new minor 2.x version that adds the deprecation/post-install warning, thanks for reminding me.

**Comment by ksol** [comment]
Closing this. About the unchecked tasks, we'll reconsider them at a later time.

**Comment by EtienneM** [comment]
> Closing this. About the unchecked tasks, we'll reconsider them at a later time.

I'm kind of afraid these unchecked tasks get lost. What are you planning so that we don't forget about them?

**Comment by ksol** [comment]
The first 3, nothing. They will be raised again by usage if needed. The fourth one is different, I'll file a ticket for it

**Comment by EtienneM** [comment]
OK, thanks :)
